### ISSUE TITLE
can't seem to enable slaveOk

### ISSUE THREAD

**Issue by drdamour** [nosqlclient/nosqlclient#106]
I don't see a checkout box for slaveOk (secondary ok).  I tried uri with 

mongodb://user:pass@host.prod/dbName?slaveOk=true

but still get the error on connect of

Couldn't connect: not master and slaveOk=false

**Comment by rsercano** [comment]
Hello,

regarding a stackoverflow answer:

> That means you're trying to read from a secondary node in a replica set, you can only read from the primary node by default.
> 
> You can allow a secondary node to accept reads by running rs.slaveOk() in a mongo shell that is connected to that secondary node. Allowing reads from a secondary is not recommended, because you could be reading stale data if the node isn't yet synced with the primary node.

Therefore, you need to do this in your replica set to allow Mongoclient connect your server.

Cheers

**Comment by drdamour** [comment]
@rsercano that is NOT what needs to happen.  rs.slaveOk is a call the client makes to say that the CURRENT ESTABLISHED SESSION allows queries against slaves.  mongo client needs to offer the ability to set this option on a connect.

PLEAS REOPEN!!

**Comment by rsercano** [comment]
@drdamour I will investigate this further mate.

**Comment by rsercano** [comment]
Hello @drdamour,

as I investigated a little bit further, I saw slaveOK has been deprecated since 2011-2012 release of mongodb. 

You need to use read preferences in your URL to use mongoclient. Have a look at [here](https://docs.mongodb.com/v3.0/reference/read-preference/#secondaryPreferred), there's an example url [here](https://gist.github.com/saintc0d3r/7f3d2191669a627fdfb6)

But I'll implement a change to set this variable simple as checking a checkbox.

**Comment by drdamour** [comment]
k I'll try it out.

by not having slaveok as an option it.makes.it not work.for older mongos DBS...not sure how far back you want to support.

heres the equivalent request in robomongo https://github.com/paralect/robomongo/issues/84

**Comment by rsercano** [comment]
MongoDB 2.4 is not supported anymore, even for the 2.6 support will be end soon. Which version are you using currently ? 

p.s. 2.6 end of life discussion can be found [here](https://jira.mongodb.org/browse/SERVER-22492)

**Comment by drdamour** [comment]
we have 2.2 2.4 2.6 etc all running...just cause it's not in support
doesn't mean enterprises don't run em.

**Comment by rsercano** [comment]
I didn't mean that of course, but I'm not planning to support unsupported mongodb versions since it's really hard to combine all the new features with the legacy ones. Therefore 2.6 should be supported by Mongoclient. Soon I'm planning to focus on replicas and customize mongoclient regarding them. 

Let me know if your issue not getting fixed by this enhancement

**Comment by drdamour** [comment]
works great on my 2.6.8 version
couldn't get it going in 2.2, but that's understandable.

thanks!
