### ISSUE TITLE
Replacing MacOS X binary removes saved connections

### ISSUE THREAD

**Issue by ajmas** [nosqlclient/nosqlclient#178]
I just replaced the MacOS X binary with a new one and find the list of connections has been reset. Where are they being saved on disk? This suggests it may be in the application folder itself?

**Comment by rsercano** [comment]
Hello,

unfortunately currently there's no migration chance. But in the newest version of mongoclient you don't have to create seperate connections for your each seperate database on same server. 

Since meteorJS has changed their mongodb engine it's impossible to migrate from 1.2.0 to 1.3.0. But for the next releases I've planned to add this migration feature, will just leave this to here for further reference.

Thank you so much for the feedback,
Cheers

**Comment by rsercano** [comment]
Resolved by last update, will be live with 1.4.0 but unfortunately there's no backward comparability for data migration.
