### ISSUE TITLE
.

### ISSUE THREAD

**Issue by mlibre** [nosqlclient/nosqlclient#183]
.

**Comment by rsercano** [comment]
Hello,

are you using URL connection ? And what error do you get ?

**Comment by mlibre** [comment]
sorry for late respond.
mongoclinet say:  
...  mongoclinet support `http` ...   
And my input/url is `mongodb://localhost:27017/example`.
this is not `http`. it work on node. i write like official mongo document.

**Comment by rsercano** [comment]
Hi,

when you execute this: **export ROOT_URL=mongodb://localhost:27017/health** that means you're trying to change root_url of mongoclient's startup. But there shouldn't be mongodb in this URL, since that's the one which you'll access mongoclient from browser. It's not about mongodb in any way. 

While connecting to a mongodb instance you need to create a new connection in **mongoclient** and set your parameters there.

**Comment by mlibre** [comment]
tnx. so i must change/set URL for mongoclient.
btw, in this page of `mongo` doc. `https://docs.mongodb.com/ecosystem/tools/http-interfaces/#http-status-interface'. they say `mongodb` deprecate HTTP interface since 3.2(current version).

**Comment by rsercano** [comment]
Mongoclient is a third party application and it's nothing about mongodb itself. Actually you don't have to set ROOT_URL unless you want to change localhost:3000 to something else like localhost:3000/mongoclient

Also you can try to use distributions instead of trying to build meteor application

**Comment by mlibre** [comment]
sr. i had big misunderstanding. my question was totally wrong :)
remove this issue at all :)
i get it now.
