### ISSUE TITLE
About CPU using

### ISSUE THREAD

**Issue by yuchting** [nosqlclient/nosqlclient#260]
Hi all,
I am a coder, but I am not good at node and JS, so I don't know why the node processes were always using the CPU? I don't open any web page from MongoClient.

What is the node process doing? How can I know about this? Or have I made some mistake in installing?

Thanks in advance!

![qq 20161214133029](https://cloud.githubusercontent.com/assets/1817716/21170716/00ee36ce-c202-11e6-945a-c2fe9c77ba96.jpg)

**Comment by rsercano** [comment]
Hello 

that doesn't seem too much to me, are you using a portable of mongoclient ? And what's your operating system ?

**Comment by yuchting** [comment]
Thanks for quick reply, it's not a serious problem, I just curious about the CPU using, in common sense, the process will sleep without any jobs. So I suspend whether I make some mistake config when I installing.

I install mongoclient in CentOS 7 x64 (Linode VPS), it's a web application version, I followed [this URL](https://github.com/rsercano/mongoclient/wiki#31-compile-from-source-browser-edition) to install.

I visit it my firefox browser, all are right in browser.

**Comment by rsercano** [comment]
Oh I see, that's probably about meteorJS itself, but if you keep mongoclient at homepage (which database statistics are getting pulled every 5-7 seconds) then it's totally normal to have such a resource usage. If you're not, then it should be about meteorjS, unfortunately I don't know the root cause of the issue on meteor side.

**Comment by rsercano** [comment]
#255
