### ISSUE TITLE
Where has the save button gone?

### ISSUE THREAD

**Issue by djdmorrison** [nosqlclient/nosqlclient#298]
I believe there used to be a save button that would allow you to edit a document directly in the results panel, and save it to the collection, without having to fiddle with update commands. 

Where has it gone?

**Comment by rsercano** [comment]
Hello @djdmorrison 

It's still there for `findOne`, but for `find` there's no button in version **1.5.0**. Because it was causing a lot of trouble, now in 1.6.0 I've implemented it again, but it's enhanced, what that mean is it finds out changed, inserted, deleted documents and queries database only for them, not for the all result set. 

To use this feature, you can use [docker](https://hub.docker.com/r/mongoclient/mongoclient/), or [compile from source](https://github.com/rsercano/mongoclient/wiki#31-compile-from-source-browser-edition), or wait me to release 1.6.0 (mid February)

Cheers

**Comment by djdmorrison** [comment]
Ah so it is! Thanks @rsercano ! I also found East Edit under the Management section which will work for now. 

Thanks for your work!

**Comment by rsercano** [comment]
@djdmorrison also easy edit won't be there anymore in the newest version, since find **SAVE** button will be enough for all operations :)
