### ISSUE TITLE
I want to start MongoClient as service but MeteorJS crashes

### ISSUE THREAD

**Issue by olivierapex** [nosqlclient/nosqlclient#323]
> All in the title ... really nice tool, but it suck as fuck meteor ... What the hell did you think about !? ... Yeah I'm rsercano and I made a fucking software (really usefull), but no fucking one will be able to use it because is fucking require meteor shit that crash and blow shit all time...
> I know you will delete my issue, but you will know the most of the people opinion now... 
> 
> PS: I love you too :)

Hello,

I really love mongoclient, and appreciate your work. Mongoclient gives us to chance of managing our databases way more easier than other tools, even than paid tools. But there's one problem, I'm trying to make mongoclient work as a web application  but it stuck all the time, I guess it's a meteor issue. Why did you choose meteor ? As far as I know it's not very popular.

Thanks in advance,
Sincerely,
Oliver

**Comment by rsercano** [comment]
Hello @olivierapex 

First of all are you drunk ? Please do not text to your ex girlfriend, that's for your own good. 
Secondly, thanks for your great opinions, people like you encourage me all the time to continue development on mongoclient. Just tell me which part crashes and I'll help you, on the other hand I strongly recommend to [use docker ](https://hub.docker.com/r/mongoclient/mongoclient/)
Thirdly, I chose meteorJS because it was so popular when I started this project, but as you know in software world everything changes so fast, apart from that meteor comes with a bunch of ease for me.

And finally, I've edited your issue just to show you there're more than one way to tell people what you think, in my opinion you wrote nothing wrong, but after you and me,  people will come and read these issues for sure. Let's just keep issues neat for them. 

PS: I already mentioned I missed you in mongoclient :)

Thanks again,
Sercan

**Comment by crtmneric** [comment]
@olivierapex 
Yeah I'm @olivierapex and I made a fuckin issue(really shitty),but everyone can see my trash comments right now.i couldn't make something like mongoclient coz i dont even know what is meteor js and how to use docker.Now i blow shit on peoples efforts. Last one think i love red cars and probably there will not be enough money to pay for it.
