### ISSUE TITLE
Special character in password while using shell cause failed authentication

### ISSUE THREAD

**Issue by HLFH** [nosqlclient/nosqlclient#341]
Hi,

Related to: https://github.com/mongoclient/mongoclient/issues/83

Special characters are not fully supported with mongoclient.
Is #83 correctly fixed for the Shell tab, for example?

## Expected Behavior
When I press Enter on the Mongo Shell, I should get answers, for example with `show dbs`

## Current Behavior
When I press Enter on the Mongo Shell, I got no answer.

## Possible Solution
Support completely special characters.

## Steps to Reproduce (for bugs)
1. Create a Connection
2. Connect
3. Go to Shell
4. Obtain the following error:

> SCRAM-SHA-1 authentication failed for myuser on admin from client 127.0.0.1:53088 ; AuthenticationFailed: SCRAM-SHA-1 authentication failed, storedKey mismatch

## Context
Connect with a secure password including special characters.

## Your Environment
* Mongoclient version used: master
* Environment name: server
* Operating System and version: Ubuntu 16.04

**Comment by rsercano** [comment]
Thank you so much for reporting this, #83 is a quite old issue and shell feature wasn't there when it was implemented. I'll check and fix this issue asap, sorry for the inconvenience.

**Comment by rsercano** [comment]
Hello again @HLFH unfortunately this bug comes from MongoDB itself. They don't support percentage encoding in URL as of 3.4.x. And it's too complicated to handle this on Mongoclient side for now, but I'll try to do my best as soon as I get some spare time. 

Here you can track this bug:
- [SERVER-27997](https://jira.mongodb.org/browse/SERVER-27997)
- [SERVER-25059](https://jira.mongodb.org/browse/SERVER-25059)

I'll leave this issue open but will remove 2.0.0 milestone for now. And as I mentioned will do my best to solve this on Mongoclient side.

**Comment by HLFH** [comment]
Hi @rsercano 

Thank you. 

I am using MongoDB 3.4.3.

Thank you for the details. As a workaround, I will manage without these kind of special characters for now.

**Comment by HLFH** [comment]
@rsercano Hi. Is that fixed? I think it is, isn't it?

**Comment by rsercano** [comment]
Hi @HLFH 

it's fixed in MongoDB 3.5.x versions, that means whenever stable 3.6 version is released for MongoDB, you can switch to it from inside of **Nosqlclient** and it should work then.
