### ISSUE TITLE
FR: mask the password in the docker log

### ISSUE THREAD

**Issue by dandv** [nosqlclient/nosqlclient#496]
When checking the Docker log, I see messages containing the full connection string, including the password in clear text. This may be insecure.

![image](https://user-images.githubusercontent.com/33569/55768308-01707780-5a42-11e9-895b-269d5fceeb91.png)

**Comment by rsercano** [comment]
In fact this's only logged if you haven't set a log level, you can set it with `MONGOCLIENT_LOG_LEVEL` environment variable, just change it to `info` and that log will disappear because it's being logged with `debug` level. This's fixed with #459 

I'll add this to the documentation with the release. And you can check our latest update about [late release here](https://medium.com/@mongoclient/why-does-it-take-forever-to-release-4-0-0-50eb66c1dc5e)
