### ISSUE TITLE
Desktop distribution?

### ISSUE THREAD

**Issue by ajmas** [nosqlclient/nosqlclient#536]
I have seen a number of ticket indicating that the desktop distribution is no longer supported, which kinda sucks for me.

I couldn't see a blog post or a ticket on this subject? Can you explain your reasoning, at least here or in the website FAQ? For example, if it is a workload issue, would you accept a community effort to continue providing a desktop version?

**Comment by rsercano** [comment]
Hello @ajmas there's not really a large number of users that are using desktop distributions and it really requires too much effort since I need a linux, a mac and a windows computer to compile those distributions, which I don't have 3 of them. 

Additionally, I'm the only one who commits to this project from the beginning and currently I'm really in a life changing situation for the last couple of months, so I'm just taking care of huge bugs, or major updates (even can't look at these 2 for the last couple of weeks) otherwise couldn't find any spare time to continue improvements which is even sad for me. 

I'm hoping to continue those after I just settle my life a bit, but desktop dstributions are really a huge effort and a community support for anything on this project is always welcome, if you could provide them I would be more than glad to add them to the releases, otherwise I (a single lonely developer) already put a huge effort on this project to provide a tool to community with no support except my close friend @kocabas.

**Comment by ajmas** [comment]
That's fair and I can't fault you for that. Sanity comes first, even more so when you aren't getting paid for the work.

If I understand it is the 'nosqlclient-electron' which serves as the base for the desktop distribution? When I have a bit of time myself I can see how I could contribute. BTW would a gitter channel for the project be of interest?

**Comment by rsercano** [comment]
Thanks mate, here we have a slack channel: https://communityinviter.com/apps/nosqlclient/nosqlclient :) Just let me know if you can't understand anything I would be happy to help
