### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by meepeek** [nosqlclient/nosqlclient#55]
The UI is pretty but still hard to use. You can use 3T MongoChef as a model for improvement. The features I would like to propose are:
1. Ability to connect DB without providing DB name. The client connect to the host and then read the DB available for user selection.
2. Ability to add new document to existing collection
3. Replace flipping transition with something else. IMO it make the app looks cheap.

Other than that, so far so good. The app has the prettiest UI among Mongo GUI clients.

**Comment by rsercano** [comment]
Hello, 

Thanks for your kind opinions. I already read your feedback about transitions :) But in fact I couldn't understand what do you mean exactly by transitions? Do you mean modal window openings? 
1. This is already in the list,  but since I'm the only one who works on this project, it takes some time sorry for the inconvenience. 
2. Easy edit section will be improved for this purpose. And I have some other easy to browse database features which I plan for another release. 
3. As I said, can you please be more specific about flip transitions? 

Thanks and Best Regards

**Comment by meepeek** [comment]
It was when I click add new collection. the modal will appear with an effect like you flip a card horizon, but it feels more like flipping a giant whiteboard.

It may looking better if the modal was a small one. Either way, there's many better effect though. IMO zoom or fade are smoother.

**Comment by rsercano** [comment]
Thanks for your suggestions, I will consider changing it with a better one

**Comment by rsercano** [comment]
1.1.0 includes modal window enhancements. For other suggestions I've created another issues #61 #31
