### ISSUE TITLE
Couldn't connect: not master

### ISSUE THREAD

**Issue by mnowotka** [nosqlclient/nosqlclient#57]
Hi,

Thanks a lot for this app, it works great for my local server. However, when I'm trying to connect to the remote server I'm getting "Couldn't connect: not master". The same connection details work fine with other Mongo client GUI (Robomongo). What can be wrong here?

![screen shot 2016-04-25 at 10 02 22](https://cloud.githubusercontent.com/assets/837119/14778789/df44af5e-0acc-11e6-8a8f-5b04659072be.png)

**Comment by rsercano** [comment]
Hello,

this happens when you are trying to connect a slavery server instead of master when replica set is installed. You would have a chance to fix this by providing master host in connection URL, with the slavery ones, but mongoclient version 1.0.0 doesn't support URL connections.

I'm now implementing this change, in version 1.1.0 you can use URL to connect your databases, furthermore, for an another release I'm planning to add advanced replica set support which will make connecting and browsing replicas much easier. 

Related issues: #50 and #12 

Thanks for your contribution :)

**Comment by mnowotka** [comment]
Yes, the "advanced replica set support which will make connecting and browsing replicas much easier" is something that I'm after :) Is there any feature request issue I can subscribe to in order to get notified when this is implemented?

**Comment by rsercano** [comment]
You can add yourself as a watcher for #12 and #50, #50 is planned for the next release and it will let you connect via URL as I said. This is kind-of not super but will do the job :)

Regards

**Comment by mnowotka** [comment]
OK, thanks!
