### ISSUE TITLE
Edit user function

### ISSUE THREAD

**Issue by dfanchon** [nosqlclient/nosqlclient#64]
When connecting with a MongoDB URI and trying to edit a user, I get the following error: Couldn't fetch userInfo: '.' is an invalid character in a database name. The connection string contains dots.
But if I check the checkbox(?) next to the Edit User button everything seems to be ok.

**Comment by rsercano** [comment]
Hello
The checkbox lets you to manage admin database instead of the active one. Can you please share your connection string after last slash (/) (excluding host/port/username/password info)

**Comment by dfanchon** [comment]
Hello
The connection string uses a replicaset, and don't provide a database name (so the driver default to admin db as quoted on the MongoDB doc).

Example: mongodb://user:password@ip1:port1,ip2:port2?replicaSet=replicasetsetname

I think your code explicitly parses the connection string to find the database name.

Thanks

**Comment by Dixeet** [comment]
In top_navbar.js, Template.topNavbar.parseDatabaseNameFromUrl you just have to change 
`catch (e) {
        return "";
    }`
by
`catch (e) {
        return "admin";
    }`
The connection created was without database in the url. In this case, the mongodb driver connects itself to the admin database but in your code if you dont have explicitly the database name some functions don't work (for example User Management)

**Comment by rsercano** [comment]
Hi,

@dfanchon that's correct, since as @Rodrive mentioned mongoclient needs databasename for some features. 

@Rodrive that's a nice point. I will gladly accept a pull request, or will do it myself this evening, since I'm at work currently I can't fix it right now. But as far as I remember I was checking for database name and if it's empty it shouldn't let you to create a connection, will check this as well.

Additionally, currently as you said, mongoclient is dependent to database name. Whenever #31 is fixed, database name will be no longer required. 

Warm Regards

**Comment by rsercano** [comment]
https://docs.mongodb.org/manual/reference/connection-string/#standard-connection-string-format
