### ISSUE TITLE
Table View Option

### ISSUE THREAD

**Issue by kaue** [nosqlclient/nosqlclient#66]
Would be great to have a Table view option like MongoChef.

**Comment by rsercano** [comment]
Definitely in queue, maybe I can put this to next release. Thanks for your suggestion :)

**Comment by rsercano** [comment]
added enhanced save button to find query to resolve this.

**Comment by HLFH** [comment]
@rsercano I do not understand how to get a table/sql view. Could you explain me how to do that? Do you have screenshots? Within collections, I see Code/Form/Text/Tree/View to print the data but no "Table".

**Comment by HLFH** [comment]
Related to: https://github.com/josdejong/jsoneditor/issues/402

**Comment by rsercano** [comment]
Hello @HLFH 

**Jsoneditor** is one of the components that is being used by Mongoclient, and you can switch to see those type of views as you mentioned or to **Aceeditor** if you're uncomfortable with it, but we decided not to keep a "table" view into Mongoclient. 

Because to me, it's non-sense to show a JSON data in a table view.  Sorry for dissapointment.

**Comment by HLFH** [comment]
Ok, thank you @rsercano for the details, I am losing a lot of time to compare fields & values with the other views, so I switched to the one I was talking about.
