### ISSUE TITLE
User auth, drop database and drop collections actions can be disabled?  use case production env

### ISSUE THREAD

**Issue by ys-roposo** [nosqlclient/nosqlclient#72]
Can mongoclient support user auth so as can be used in a team setup ? 
Also drop database or collection are prominently used in the UI, not good for production use as any team member could mistakenly click on a disaster. Any suggestion if the UI could be modified to remove these actions or create a ACL to not allow delete/drop actions on any DB ?

**Comment by rsercano** [comment]
Hello,

I understand your concerns. First of all changing UI for user management is not a good option, you have to do it over mongodb. Because if some kind of bug occurs and someone who shouldn't have drop db right can click over it, you can't revert it back, it would be a disaster. 

Secondly mongodb presents a great way to manage database users. If you  want to restrict a user to drop/delete something just give him/her only read right. I highly recommend you to read [here](https://docs.mongodb.org/manual/reference/privilege-actions/) You can simply set up custom roles with built-in privileges of mongodb then give these roles to corresponding people. 

Afterwards, you can distribute Mongoclient complacency to every member of your team :)

If you have any further questions let me know.

Warm Regards

**Comment by rsercano** [comment]
Additionally Mongoclient has a user management section which makes your life easier at this point :)
