### ISSUE TITLE
MongoClient Authorization

### ISSUE THREAD

**Issue by nhahv** [nosqlclient/nosqlclient#76]
Hi. I'm using this application to manage and monitor my mongodb server. 
Also, this application is installed on server.In my case, there're some prolems: 
- MongoClient don't have authorization to access the web-ui.
- MongoDB Connections are stored on MongoClient but are **accessible to everyone** not only our team members, but also **all people** from **anywhere**.

_So, would you mind if adding some features as:_
- Store connection configurations on web browsers local storage
- Authorized user can store connection configurations as their properties

**_Thanks and regards.**_

**Comment by rsercano** [comment]
Hello,

first of all thanks for using mongoclient. Are you using mongoclient on a linux machine ?
Adding authorization to mongoclient means changing whole platform's (mac,windows,linux portables) behaviour which is not an expected behaviour most of the time. Nevertheless I will evaluate your requests. 

But I wonder why don't you restrict access via a basic firewall such as [UFW](https://help.ubuntu.com/community/UFW)  (if you are on a linux machine)?

Warm Regards
